# Generated by Django 5.1.4 on 2025-01-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_status_alter_transaction_counterparty_and_more'),
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='offered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_transactions', to='wardrobe.wardrobeitem'),
        ),
    ]
